### ISSUE TITLE
Basic HTTP noit check

### ISSUE THREAD

**Issue by robert-chiniquy** [virgo-agent-toolkit/agent-poller-noit-parity#4]
Add a basic test to start noit and stratcon, and validate that we can configure an HTTP check in noit and receive metrics from stratcon.

**Comment by ynachiket** [comment]
https://gist.github.com/ynachiket/4a5ae819bf906b85bfe0

The last container in the above gist runs noit client tests https://github.com/virgo-agent-toolkit/noit_client/blob/master/test/test_noit_client.js against the noit container.
